/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.serialization") version "2.0.20"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.clikt)
    implementation(libs.jsoup)
    implementation(libs.okhttp)
    implementation(libs.json)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.mockk)
}

kotlin {
    jvmToolchain(17)
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}